window.PizzaTypes = {
  normal: "normal",
  spicy: "spicy",
  veggie: "veggie",
  fungi: "fungi",
  chill: "chill",
}

window.Pizzas = {
  "s001": {
    name: "Shawn Michaels",
    description: "Heart Break Kid",
    type: PizzaTypes.spicy,
    src: "/images/characters/pizzas/sm.png",
    icon: "/images/icons/spicy.png",
    actions: [ "damage1",  "saucyStatus", "clumsyStatus"],
  },
  "s002": {
    name: "Yokozuna",
    description: "A fat Samoan",
    type: PizzaTypes.spicy,
    src: "/images/characters/pizzas/zoons.png",
    icon: "/images/icons/spicy.png",
    actions: [ "damage1", "saucyStatus", "clumsyStatus" ],
  },
  "v001": {
    name: "Doink",
    description: "the Clown",
    type: PizzaTypes.veggie,
    src: "/images/characters/pizzas/dtc.png",
    icon: "/images/icons/chill.png",
    actions: [ "damage1", "saucyStatus", "clumsyStatus" ],
  },
  "v002": {
    name: "Sting",
    description: "The Man they call Sting",
    type: PizzaTypes.veggie,
    src: "/images/characters/pizzas/sting.png",
    icon: "/images/icons/veggie.png",
    actions: [ "damage4" , "damage5", "saucyStatus"],
  },
  "f001": {
    name: "Razor Ramon",
    description: "The Bad Guy",
    type: PizzaTypes.fungi,
    src: "/images/characters/pizzas/rr.png",
    icon: "/images/icons/fungi.png",
    actions: [ "damage6" , "saucyStatus", "clumsyStatus"],
  },
  "f002": {
    name: "Lex Luger",
    description: "The Total Package",
    type: PizzaTypes.fungi,
    src: "/images/characters/pizzas/lex.png",
    icon: "/images/icons/fungi.png",
    actions: [ "damage2" , "saucyStatus", "clumsyStatus"],
  },
  "DtC": {
      name: "Doink",
      description: "The Clown",
      type: PizzaTypes.fungi,
      src: "/images/characters/pizzas/DtC.gif",
      icon: "/images/icons/fungi.png",
      actions: [ "damage1" , "saucyStatus", "clumsyStatus"],
  },
  "Lex": {
    name: "Lex Luger",
    description: "The Total Package",
    type: PizzaTypes.fungi,
    src: "/images/characters/pizzas/lex.png",
    icon: "/images/icons/spicy.png",
    actions: [ "damage2" , "saucyStatus", "clumsyStatus"],
},
"RF": {
  name: "Ric Flair",
  description: "Nature Boy",
  type: PizzaTypes.normal,
  src: "/images/characters/pizzas/rf.png",
  icon: "/images/icons/chill.png",
  actions: [ "damage7", "saucyStatus", "clumsyStatus" ],
},
"RR": {
  name: "Razor Ramon",
  description: "The Bad Guy",
  type: PizzaTypes.fungi,
  src: "/images/characters/pizzas/rr.png",
  icon: "/images/icons/chill.png",
  actions: [ "damage6", "saucyStatus", "clumsyStatus" ],
},
"Dave": {
  name: "Dave Meltzer",
  description: "I drive a racecar bed.",
  type: PizzaTypes.fungi,
  src: "/images/characters/pizzas/meltzer.png",
  icon: "/images/icons/chill.png",
  actions: [ "damage6", "saucyStatus", "clumsyStatus" ],
},
"ko": {
  name: "Kenny Omega",
  description: "69 me Don!",
  type: PizzaTypes.fungi,
  src: "/images/characters/pizzas/ko.png",
  icon: "/images/icons/chill.png",
  actions: [ "damage6", "saucyStatus", "clumsyStatus" ],
},
"BT": {
  name: "Booker T",
  description: "5 Time WCW Champion",
  type: PizzaTypes.fungi,
  src: "/images/characters/pizzas/BT.png",
  icon: "/images/icons/spicy.png",
  actions: [ "damage8", "saucyStatus", "clumsyStatus" ],
}
}